### PR TITLE
Java parsing

### PR DESCRIPTION
**Pull request by Istyatur**
adds the java parser, hierarchy analysis, and reiminfir install.

### CODE REVIEW

**Comment by chameco** [comment]
Regarding install_dependencies.sh, have you already tested using `pip` or `easy_install` to install `python-graph-tool` rather than the system-native package manager? It would increase portability and remove a lot of the PPA-related complexity from the script. Of course, if you've already tested and `pip` does not work correctly, we can continue using the current logic. I would like to move dependency installation to a phony Makefile hook eventually, but for now leaving it in a separate script is fine.

Other than that, we can merge as soon as Travis checks pass on the Python code, which should be a fairly minor change.

**Comment by Istyatur** [comment]
Although graph-tool is a Python library, it is implemented in C++, and thus has C++ dependencies such as Boost, CGAL and expat, which are not installable via Python-only package management systems such as pip or EasyInstall.

**Comment by chameco** [comment]
Ah, noted. This way is probably best then.

It looks like Travis is failing because of `print` statements (versus the Python 3 style `print` function). We're (trying, at least) to use Python 3 for new code, so that should be a very simple change.

**Comment by chameco** [comment]
Your last change will break Travis, as `apt-get` without `-qq` will prompt for input and never exit. You shoudn't need to install `python-graph-tool` in Travis, as only Pylint is running (the code is never actually executed).

**Comment by Istyatur** [comment]
pylint has errors for undefined symbols like
E: 65, 0: Undefined variable 'graph_draw' (undefined-variable)
so it needs some knowledge of graph tool... if it doesn't need it in its entirety what does it need?

**Comment by Istyatur** [comment]
and the --yes --force-yes (needed  because of a missing validation key) should prevent it from needing input.

**Comment by chameco** [comment]
That's caused by the unconditional import `from graph_tool.all import *`, which is not allowed by PEP 8 (you'll notice the `wildcard-error` lines earlier in Travis output). The preferred style would be `from graph_tool import graph_draw`, etc.

**Pull request merged**
